# Generated by Django 5.1.3 on 2025-03-01 20:23

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=orders.models.generate_order_id, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
